# Generated by Django 2.1.3 on 2018-11-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=80, verbose_name='开盘名称')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, max_length=8, unique=True, verbose_name='价格')),
                ('area', models.IntegerField(unique=True, verbose_name='面积')),
                ('floor', models.IntegerField(verbose_name='所处楼层')),
                ('image', models.ImageField(upload_to='', verbose_name='图片信息')),
                ('address', models.TextField(verbose_name='地址')),
                ('message', models.CharField(max_length=80, verbose_name='其他信息')),
            ],
        ),
    ]
