# Generated by Django 2.1.3 on 2018-11-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiYang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='create_time',
            field=models.DateTimeField(auto_created=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, unique=True, verbose_name='价格'),
        ),
    ]
