# Generated by Django 2.1.3 on 2018-11-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiYang', '0002_auto_20181109_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(max_length=80, verbose_name='价格'),
        ),
    ]
