# Generated by Django 2.1.3 on 2018-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiYang', '0003_auto_20181109_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='图片信息'),
        ),
    ]
